export const uiText = {
  fr: {
    htmlLang: "fr",
    languageToggle: "EN",
    brandEyebrow: "Gameplay Programmer Portfolio",
    introCopy:
      "Portfolio interactif consacre a la programmation gameplay, aux systemes temps reel et a la mise en scene de projets techniques.",
    overviewTrigger: "Pas le temps pour jouer ? Clique ici",
    leaderboardTrigger: "Leaderboard",
    closePanel: "Masquer la fiche",
    heroEyebrow: "Hall central",
    heroTitle: "Visite libre en vue FPS.",
    heroBody:
      "Clique dans la scene pour capturer la souris, deplace-toi en ZQSD ou WASD, maintiens Shift pour sprinter, Space pour sauter, puis vise un stand et appuie sur E pour ouvrir sa fiche.",
    combatEyebrow: "Survivor Slime",
    combatTitle: "Arc Blaster",
    combatDefault:
      "Clic gauche pour tirer. Les slimes continuent de repop tant que tu restes dans l'arene.",
    cookingEyebrow: "VR Cooking",
    cookingTitle: "Service burgers",
    cookingRushStable: "Cuisine stable",
    cookingComboBase: "Combo x1",
    cookingHeldEmpty: "Mains vides",
    cookingHintDefault: "Vise une station et clique ou appuie sur E pour interagir.",
    drivingEyebrow: "DrivingSim",
    drivingTitle: "Urban Test Loop",
    drivingModeOnFoot: "A pied",
    drivingHintDefault:
      "Approche-toi de la voiture et clique ou appuie sur E pour prendre le volant.",
    drivingRaceIdle: "Boucle en attente",
    drivingRaceScore: "Score circuit",
    projectVideoEyebrow: "Presentation video",
    projectVideoFrameLabel: "Trailer / gameplay capture",
    metaEngine: "Moteur",
    metaFocus: "Focus",
    metaContext: "Contexte",
    metaRole: "Role",
    metaYear: "Periode",
    metaStack: "Stack",
    overviewEyebrow: "Fast Track",
    overviewTitle: "Tous les projets en un coup d'oeil",
    overviewBody:
      "Une lecture rapide du portfolio si tu n'as pas le temps de faire la visite interactive.",
    closeOverview: "Fermer",
    leaderboardEyebrow: "Leaderboard partage",
    leaderboardTitle: "Scores des joueurs",
    leaderboardBody:
      "Choisis un nom de joueur pour cumuler les points de Survivor Slime, VR Cooking et DrivingSim et partager le score avec les autres visiteurs.",
    closeLeaderboard: "Fermer",
    leaderboardCurrentEyebrow: "Joueur actif",
    leaderboardCurrentEmpty: "Aucun joueur",
    leaderboardCurrentTotal: "Total cumule",
    leaderboardNameLabel: "Nom du joueur",
    leaderboardNamePlaceholder: "Entre un nom",
    leaderboardSave: "Activer",
    leaderboardHint:
      "Le score cumule les points de combat, de cuisine et de course. Les donnees sont synchronisees avec le site.",
    leaderboardListEyebrow: "Classement global",
    leaderboardEmpty:
      "Aucun score enregistre pour l'instant. Cree un joueur puis lance un mini-jeu pour alimenter le classement.",
    leaderboardMetricTotal: "Total",
    leaderboardMetricSlime: "Slime",
    leaderboardMetricCooking: "Cooking",
    leaderboardMetricDriving: "Driving",
    leaderboardMetricUpdated: "Derniere activite",
    testerSummaryEmpty: "Aucun joueur actif",
    testerSummaryLabel: "Joueur",
    hintCapture: "Clic scene pour capturer la souris",
    hintMove: "ZQSD / WASD pour marcher, Shift pour sprint, Space pour sauter",
    hintOpen: "E pour ouvrir, Echap pour liberer",
  },
  en: {
    htmlLang: "en",
    languageToggle: "FR",
    brandEyebrow: "Gameplay Programmer Portfolio",
    introCopy:
      "Interactive portfolio dedicated to gameplay programming, real-time systems and the staging of technical projects.",
    overviewTrigger: "No time to play? Click here",
    leaderboardTrigger: "Leaderboard",
    closePanel: "Hide project sheet",
    heroEyebrow: "Central hall",
    heroTitle: "Free-roam FPS visit.",
    heroBody:
      "Click in the scene to capture the mouse, move with ZQSD or WASD, hold Shift to sprint, Space to jump, then aim at a stand and press E to open its sheet.",
    combatEyebrow: "Survivor Slime",
    combatTitle: "Arc Blaster",
    combatDefault:
      "Left click to shoot. Slimes keep respawning as long as you stay inside the arena.",
    cookingEyebrow: "VR Cooking",
    cookingTitle: "Burger service",
    cookingRushStable: "Kitchen stable",
    cookingComboBase: "Combo x1",
    cookingHeldEmpty: "Hands empty",
    cookingHintDefault: "Aim at a station and click or press E to interact.",
    drivingEyebrow: "DrivingSim",
    drivingTitle: "Urban Test Loop",
    drivingModeOnFoot: "On foot",
    drivingHintDefault:
      "Get close to the car and click or press E to take the wheel.",
    drivingRaceIdle: "Loop idle",
    drivingRaceScore: "Loop score",
    projectVideoEyebrow: "Video presentation",
    projectVideoFrameLabel: "Trailer / gameplay capture",
    metaEngine: "Engine",
    metaFocus: "Focus",
    metaContext: "Context",
    metaRole: "Role",
    metaYear: "Period",
    metaStack: "Stack",
    overviewEyebrow: "Fast Track",
    overviewTitle: "All projects at a glance",
    overviewBody:
      "A quick read-through of the portfolio if you do not have time for the interactive visit.",
    closeOverview: "Close",
    leaderboardEyebrow: "Shared leaderboard",
    leaderboardTitle: "Player scores",
    leaderboardBody:
      "Pick a player name to accumulate Survivor Slime, VR Cooking and DrivingSim points and share the score with other visitors.",
    closeLeaderboard: "Close",
    leaderboardCurrentEyebrow: "Active player",
    leaderboardCurrentEmpty: "No player selected",
    leaderboardCurrentTotal: "Total score",
    leaderboardNameLabel: "Player name",
    leaderboardNamePlaceholder: "Enter a name",
    leaderboardSave: "Activate",
    leaderboardHint:
      "The score combines combat, cooking and driving points. Data is synced with the website.",
    leaderboardListEyebrow: "Global ranking",
    leaderboardEmpty:
      "No score recorded yet. Create a player and launch a mini-game to feed the ranking.",
    leaderboardMetricTotal: "Total",
    leaderboardMetricSlime: "Slime",
    leaderboardMetricCooking: "Cooking",
    leaderboardMetricDriving: "Driving",
    leaderboardMetricUpdated: "Last activity",
    testerSummaryEmpty: "No active player",
    testerSummaryLabel: "Player",
    hintCapture: "Click scene to capture the mouse",
    hintMove: "ZQSD / WASD to move, Shift to sprint, Space to jump",
    hintOpen: "E to open, Escape to release",
  },
} as const;
